/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LevelImport } from './routes/$level'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LevelRoute = LevelImport.update({
  id: '/$level',
  path: '/$level',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$level': {
      id: '/$level'
      path: '/$level'
      fullPath: '/$level'
      preLoaderRoute: typeof LevelImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$level': typeof LevelRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$level': typeof LevelRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$level': typeof LevelRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$level'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$level'
  id: '__root__' | '/' | '/$level'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LevelRoute: typeof LevelRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LevelRoute: LevelRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$level"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$level": {
      "filePath": "$level.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
