/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SessImport } from './routes/$sess'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SessRoute = SessImport.update({
  id: '/$sess',
  path: '/$sess',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$sess': {
      id: '/$sess'
      path: '/$sess'
      fullPath: '/$sess'
      preLoaderRoute: typeof SessImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$sess': typeof SessRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$sess': typeof SessRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$sess': typeof SessRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$sess'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$sess'
  id: '__root__' | '/' | '/$sess'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessRoute: typeof SessRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessRoute: SessRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$sess"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$sess": {
      "filePath": "$sess.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
